Update b:match_words
vhda/verilog_systemverilog.vim pull request #123
Opened 2016-10-13 14:38 UTC by r901042004

Enable using % to jump between "if-else if-else" condition.

2016-10-13 17:40 UTC, r901042004 commented
If you want to support "if-else if" statement, you can modify matchit.vim like [this](https://github.com/r901042004/matchit.zip/commit/78d491c8a07c2868ec84eb6d6bd2793c08372271).
```
if (condition) // if1
  statement;
else if (condition) //elseif1
  statement;
else if (condition) //elseif2
  statement;
```
You can use % to jump to "if1" from "elseif2".

2016-10-15 09:43 UTC, r901042004 commented
I change some script in [matchit.vim](https://github.com/r901042004/matchit.zip). 
It can solve the problem which makes the cursor jumps to incorrect position.

2016-10-17 18:10 UTC, vhda requested changes

2016-10-17 18:10 UTC, vhda commented on ftplugin/verilog_systemverilog.vim
> +    \ '\(else\s\+\)\@<!\<if\>:\<else\>\s\+\<if\>:\(`\)\@<!\<else\>\(\s\+if\)\@!,' .
Knowing that look-behind matches are very costly in Vim's regular expression engine I decided to test this in a big (not huge) SystemVerilog file. From what I can see as long as hl_matchit plugin is enabled moving the cursor around `if..else if` constructs becomes very slow. You might want to check that for yourself and maybe consider using `\zs` and `\ze` patterns in place of look-behind, whenever possible.

Given that this improvement slows down Vim and that it requires a patched matchit to work at 100%, I'd also propose that you add support for a new variable `g:verilog_matchit_elseif` to enable this feature. This way we can all use the same central plugin. Please don't forget to document this new variable in `doc/verilog_systemverilog.txt` and to update its respective tags with `:helptags`.

P.S. - Disclosure: I will very likely not use this feature because all my `else if` are written as `else begin if ... begin ...`. As an RTL developer this forces me to identify long conditions that will result in a big number of logic levels.

2016-10-18 09:50 UTC, r901042004 commented on ftplugin/verilog_systemverilog.vim
> +    \ '\(else\s\+\)\@<!\<if\>:\<else\>\s\+\<if\>:\(`\)\@<!\<else\>\(\s\+if\)\@!,' .
OK. I'll test it a few days later.
Maybe I can find a solution in modifying matchit.
I think that `else if` can be recognized as parallel case. (The condition is similar.)
```
unique if (sel==2'b00)
  out = ...;
else if (sel==2'b01)
  out = ...;
else if (sel==2'b10)
  out = ...;
else
  out = ...;
```
Not parallel case:
```
priority if (rst)
  register <= 32'd0;
else
begin
  unique if (cond==2'b00)
    register <= 32'd0;
  else if (cond==2'b01)
    register <= register+32'd1;
  else 
    register <= register;
end
```
Verilog doesn't restrict designers to use which usage.
I think that two usages can increase readability and reduce too many indents.

2016-10-18 10:15 UTC, vhda commented on ftplugin/verilog_systemverilog.vim
> +    \ '\(else\s\+\)\@<!\<if\>:\<else\>\s\+\<if\>:\(`\)\@<!\<else\>\(\s\+if\)\@!,' .
Careful, `unique` is a SystemVerilog keyword, which is still not widely used in RTL development. The "correct" way of writing a parallel statement is using `case`:

``` SystemVerilog
case (sel)
  2'b00   : out = ...;
  2'b01   : out = ...;
  2'b10   : out = ...;
  default : out = ...;
endcase
```

Obviously, being "correct" basically depends on which synthesis tool you are using and whether your code needs to be portable to other (sometimes unknown) tools.

While it also brought some interesting improvements, SystemVerilog has done wonders in reinventing the wheel and providing multiple solutions to fix the same problem (IMHO :P).

2016-10-18 13:56 UTC, vhda commented
Please don't forget to rebase your latest work over `origin/master`.

2016-12-19 12:01 UTC, vhda commented
@r901042004 did you get your changes merged into the main matchit plugin?
Do you have the updates I requested in this PR?

2017-10-09 03:21 UTC, closed without merging